# Generated by Django 5.2.5 on 2025-12-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0014_alter_solicitacaocompra_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente_aprovacao', 'Pendente de Aprovação'), ('aprovado_engenharia', 'Aprovado - Engenharia'), ('aprovada', 'Cotação - Para Iniciar'), ('rejeitada', 'Rejeitada'), ('aguardando_resposta', 'Em Cotação'), ('cotacao_selecionada', 'Cotação Recebida'), ('finalizada', 'RM Gerada'), ('a_caminho', 'A Caminho'), ('recebida_parcial', 'Recebida Parcialmente'), ('recebida', 'Recebida'), ('desativada', 'Desativada (Processada em Agregados)')], default='rascunho', max_length=20),
        ),
    ]
