# Generated by Django 5.2.5 on 2025-12-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0015_alter_solicitacaocompra_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcotacao',
            options={'verbose_name': 'Item da Cotação', 'verbose_name_plural': 'Itens da Cotação'},
        ),
    ]
