# Generated by Django 5.2.5 on 2025-12-18 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0016_alter_itemcotacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_fornecedor', to='materiais.fornecedor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(choices=[('almoxarife_obra', 'Almoxarife da Obra'), ('engenheiro', 'Engenheiro'), ('almoxarife_escritorio', 'Almoxarife do Escritório'), ('diretor', 'Diretor'), ('fornecedor', 'Fornecedor')], max_length=30),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
