# Generated by Django 5.2.5 on 2025-12-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0017_user_fornecedor_alter_user_perfil_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='condicao_sugerida_escritorio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='prazo_sugerido_escritorio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(default='Não Informada', max_length=100),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(default='PI', max_length=2),
        ),
    ]
