# Generated by Django 5.2.5 on 2025-12-18 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0018_cotacao_condicao_sugerida_escritorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotacao',
            name='origem',
            field=models.CharField(choices=[('portal', 'Portal Fornecedor'), ('manual', 'Manual Escritório')], default='portal', max_length=20),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacoes_inseridas', to=settings.AUTH_USER_MODEL),
        ),
    ]
