# Generated by Django 5.2.5 on 2025-12-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0019_cotacao_data_registro_cotacao_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='pagamento_original_escritorio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='prazo_original_escritorio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
