# Generated by Django 5.2.5 on 2025-12-18 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0020_cotacao_pagamento_original_escritorio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cotacao',
            unique_together={('solicitacao', 'fornecedor')},
        ),
        migrations.AddField(
            model_name='cotacao',
            name='conformidade',
            field=models.CharField(choices=[('verde', 'Total Conformidade'), ('amarelo', 'Atenção Comercial'), ('vermelho', 'Divergência Crítica')], default='verde', max_length=10),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='motivo_divergencia_pagamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='motivo_divergencia_prazo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='materiais.fornecedor'),
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='condicao_sugerida_escritorio',
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='prazo_sugerido_escritorio',
        ),
    ]
