# Generated by Django 5.2.5 on 2026-01-07 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0024_make_obra_required_add_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='endereco_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacoes_entrega', to='materiais.obra', verbose_name='Obra de Entrega'),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_destino', to='materiais.obra', verbose_name='Obra de Destino'),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_origem', to='materiais.obra'),
        ),
    ]
