# Generated by Django 5.2.5 on 2026-01-07 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0025_alter_cotacao_endereco_entrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='materiais.fornecedor')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
