# Generated by Django 5.2.5 on 2026-01-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0026_notificacaofornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviocotacao',
            name='data_entrega_solicitada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
