# Generated by Django 5.2.5 on 2026-01-09 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0027_enviocotacao_data_entrega_solicitada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('api_url', models.URLField(blank=True, max_length=300)),
                ('api_token', models.CharField(blank=True, max_length=300)),
                ('numero_almoxarife', models.CharField(blank=True, max_length=20)),
                ('numero_diretor', models.CharField(blank=True, max_length=20)),
                ('numero_engenheiro', models.CharField(blank=True, max_length=20)),
                ('notificar_sc_urgente', models.BooleanField(default=True)),
                ('notificar_cotacao_vencida', models.BooleanField(default=True)),
                ('notificar_rm_pendente_7dias', models.BooleanField(default=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração WhatsApp',
                'verbose_name_plural': 'Configurações WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='MetricaCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data da Métrica')),
                ('total_scs_criadas', models.IntegerField(default=0)),
                ('total_scs_aprovadas', models.IntegerField(default=0)),
                ('total_scs_em_cotacao', models.IntegerField(default=0)),
                ('total_scs_finalizadas', models.IntegerField(default=0)),
                ('total_cotacoes_enviadas', models.IntegerField(default=0)),
                ('total_cotacoes_recebidas', models.IntegerField(default=0)),
                ('total_cotacoes_vencidas', models.IntegerField(default=0)),
                ('tempo_medio_aprovacao', models.FloatField(blank=True, help_text='Em horas', null=True)),
                ('tempo_medio_cotacao', models.FloatField(blank=True, help_text='Em horas', null=True)),
                ('tempo_medio_resposta_fornecedor', models.FloatField(blank=True, help_text='Em horas', null=True)),
                ('taxa_resposta_fornecedores', models.FloatField(blank=True, help_text='Percentual', null=True)),
                ('fornecedores_mais_rapidos', models.JSONField(blank=True, null=True)),
                ('fornecedores_mais_lentos', models.JSONField(blank=True, null=True)),
                ('valor_total_cotado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_medio_cotacao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('economia_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_calculo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica de Cotação',
                'verbose_name_plural': 'Métricas de Cotações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('editado', models.BooleanField(default=False)),
                ('data_edicao', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_sc', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='materiais.solicitacaocompra')),
                ('usuarios_mencionados', models.ManyToManyField(blank=True, related_name='comentarios_mencionado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário SC',
                'verbose_name_plural': 'Comentários SC',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SugestaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_confiabilidade', models.FloatField(help_text='Score 0-100')),
                ('score_preco', models.FloatField(help_text='Score 0-100')),
                ('score_prazo', models.FloatField(help_text='Score 0-100')),
                ('score_total', models.FloatField(help_text='Média ponderada')),
                ('justificativa', models.TextField(blank=True)),
                ('data_sugestao', models.DateTimeField(auto_now_add=True)),
                ('aceita', models.BooleanField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes_ia', to='materiais.fornecedor')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes_ia', to='materiais.solicitacaocompra')),
            ],
            options={
                'verbose_name': 'Sugestão IA',
                'verbose_name_plural': 'Sugestões IA',
                'ordering': ['-score_total'],
            },
        ),
    ]
