# Generated by Django 5.2.5 on 2026-01-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0028_configuracaowhatsapp_metricacotacao_comentariosc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sc_criada_diretor', 'SC Criada - Notificação Diretor'), ('sc_aprovada_escritorio', 'SC Aprovada - Notificação Escritório'), ('cotacao_enviada_fornecedor', 'Cotação Enviada - Email Fornecedor'), ('rm_aprovada_solicitante', 'RM Aprovada - Notificação Solicitante'), ('recebimento_registrado', 'Recebimento Registrado - Notificação'), ('lembrete_cotacao_pendente', 'Lembrete - Cotação Pendente')], max_length=50, unique=True)),
                ('assunto', models.CharField(help_text='Assunto do email (deixe em branco para notificações internas)', max_length=200)),
                ('corpo', models.TextField(help_text='Corpo da mensagem. Use {variavel} para substituições dinâmicas.')),
                ('variaveis_disponiveis', models.TextField(blank=True, help_text='Lista de variáveis disponíveis para este template (ex: {numero_sc}, {solicitante}, {obra})')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_edicao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensagem Personalizada',
                'verbose_name_plural': 'Mensagens Personalizadas',
                'ordering': ['tipo'],
            },
        ),
    ]
