# Generated by Django 5.2.5 on 2026-01-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0029_mensagempersonalizada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagempersonalizada',
            options={'ordering': ['categoria', 'tipo'], 'verbose_name': 'Mensagem Personalizada', 'verbose_name_plural': 'Mensagens Personalizadas'},
        ),
        migrations.AddField(
            model_name='mensagempersonalizada',
            name='categoria',
            field=models.CharField(choices=[('notificacao_interna', 'Notificação Interna do Sistema'), ('email_fornecedor', 'E-mail para Fornecedor'), ('email_usuario', 'E-mail para Usuário Interno')], default='notificacao_interna', max_length=30),
        ),
        migrations.AlterField(
            model_name='mensagempersonalizada',
            name='assunto',
            field=models.CharField(blank=True, help_text='Assunto do email (obrigatório para e-mails)', max_length=200),
        ),
        migrations.AlterField(
            model_name='mensagempersonalizada',
            name='tipo',
            field=models.CharField(choices=[('sc_criada_diretor', 'SC Criada - Notificação Diretor'), ('sc_aprovada_escritorio', 'SC Aprovada - Notificação Escritório'), ('sc_editada_escritorio', 'SC Editada - Notificação Solicitante'), ('cotacao_recebida_almoxarife', 'Cotação Recebida - Notificação Almoxarife'), ('cotacao_atualizada', 'Cotação Atualizada - Notificação Escritório'), ('cotacao_excluida', 'Cotação Excluída - Notificação Escritório'), ('rm_aprovada_solicitante', 'RM Aprovada - Notificação Solicitante'), ('recebimento_registrado', 'Recebimento Registrado - Notificação'), ('lembrete_cotacao_pendente', 'Lembrete - Cotação Pendente'), ('fornecedor_visualizou_portal', 'Fornecedor Acessou Portal'), ('email_convite_cotacao', 'E-mail - Convite para Cotação'), ('email_lembrete_cotacao', 'E-mail - Lembrete de Cotação Pendente'), ('email_cotacao_aprovada', 'E-mail - Sua Cotação foi Aprovada'), ('email_cotacao_rejeitada', 'E-mail - Cotação Não Aprovada'), ('email_rm_enviada', 'E-mail - Requisição de Material Enviada'), ('email_sc_rejeitada', 'E-mail - SC Rejeitada pelo Diretor'), ('email_rm_aprovada', 'E-mail - RM Aprovada e Disponível')], max_length=50, unique=True),
        ),
    ]
